app-params:
    environment: DEV
    githubUsersQuantity: 10
    multiThreadSize: 1
    githubAPIMaxPageSize: 100
    dbUser: user_service
    dbPassword: 123
    dbHostName: localhost
    dbPort: 3306
    dbEngine: mysql
    dbName: greatest_users
    dbURL: jdbc:mysql://${MYSQL_HOST:localhost}:3306/greatest_users
    dbDriverClassName: com.mysql.cj.jdbc.Driver
